# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# Seed data I create to show on front end
quote1 = Quote.create(text: "If I had one hour left to live, I would spend it in math class because that never ends")
quote2 = Quote.create(text: "I used to think I was indecisive, but now I'm not sure")
quote3 = Quote.create(text: "Last night my internet went out, so I talked to my family. They seemed like cool people.")
quote4 = Quote.create(text: "The more you weigh, the harder you are to kidnap. Stay safe, eat cake.")
quote5 = Quote.create(text: "Before you judge a man, walk a mile in his shoes. After that who cares?... He’s a mile away and you’ve got his shoes!")
quote6 = Quote.create(text: "Better to remain silent and be thought a fool than to speak out and remove all doubt.")
quote7 = Quote.create(text: "Light travels faster than sound. This is why some people appear bright until you hear them speak.")
quote8 = Quote.create(text: "I don’t believe in astrology; I’m a Sagittarius and we’re skeptical.")
quote9 = Quote.create(text: "My opinions may have changed, but not the fact that I’m right.")
quote10 = Quote.create(text: "To be sure of hitting the target, shoot first, and call whatever you hit the target.")
quote11 = Quote.create(text: "Be who you are and say what you feel, because those who mind don’t matter and those who matter don’t mind.")
quote12 = Quote.create(text: "Money won’t buy happiness, but it will pay the salaries of a large research staff to study the problem.")
quote13 = Quote.create(text: "We never really grow up, we only learn how to act in public.")
quote14 = Quote.create(text: "I always arrive late at the office, but I make up for it by leaving early.")
quote15 = Quote.create(text: "A stockbroker urged me to buy a stock that would triple its value every year. I told him, ‘At my age, I don’t even buy green bananas.'")
quote16 = Quote.create(text: "Never under any circumstances take a sleeping pill and a laxative on the same night.")
quote17 = Quote.create(text: "Always remember that you are absolutely unique. Just like everyone else.")
quote18 = Quote.create(text: "As you get older three things happen. The first is your memory goes, and I can’t remember the other two.")
quote19 = Quote.create(text: "Always borrow money from a pessimist. He won’t expect it back.")
quote20 = Quote.create(text: "I can resist everything except temptation.")
quote21 = Quote.create(text: "Women are meant to be loved, not to be understood.")
quote22 = Quote.create(text: "I'm trying my best to see things from you're point of view, I just cant get my head that far up my ass.")
quote23 = Quote.create(text: "My mom asked me what am I going to do with my life... I don't even know what I'm going to have for lunch.")

image1 = Image.create(image_url: "http://digitalimagemakerworld.com/images/funny-wallpaper-hd/37665836-funny-wallpaper-hd.jpg")
image2 = Image.create(image_url: 'http://images4.fanpop.com/image/photos/24300000/Funny-Yoda-Wallpaper-star-wars-24365503-1366-768.jpg')
image3 = Image.create(image_url: 'http://sf.co.ua/13/01/wallpaper-2575295.jpg')
image4 = Image.create(image_url: 'https://images2.memedroid.com/images/UPLOADED18/504299a0205de.jpeg')
image5 = Image.create(image_url: 'http://1.bp.blogspot.com/-e2eSWm7fgAg/T5Kp6nzEsZI/AAAAAAAADjw/i_MVNLV6Gro/s1600/Funny+wallpapers+hd+3.gif')
image6 = Image.create(image_url: 'https://assets.aspeninstitute.org/content/uploads/2019/01/writing_featured.jpg')
image7 = Image.create(image_url: 'http://www.geocities.ws/giocchi27/dho.jpg')
image8 = Image.create(image_url: 'https://ak7.picdn.net/shutterstock/videos/33802027/thumb/12.jpg')
image9 = Image.create(image_url: 'https://i.imgur.com/I2V8rEk.jpg')
image10 = Image.create(image_url: 'https://images7.alphacoders.com/512/thumb-1920-512977.jpg')
image11 = Image.create(image_url: 'https://images.agoramedia.com/everydayhealth/gcms/Why-Does-Diabetes-Make-Me-So-Tired-1440x810.jpg?width=722')
image12 = Image.create(image_url: 'https://cld.activebeat.com/image/upload/t_tn,f_auto,q_auto,$h_360,$w_580/ab/2015/11/shutterstock_625957016-580x360.jpg')
image13 = Image.create(image_url: 'https://www.meme-arsenal.com/memes/0f41d42d6c23ce03ae335e89695910ab.jpg')
image14 = Image.create(image_url: 'https://scstylecaster.files.wordpress.com/2014/02/positive-thinking.jpg?w=1024&h=741')
image15 = Image.create(image_url: 'https://images.techhive.com/images/article/2016/09/7702773622_a350fa7a07_o-100683757-primary.idge.jpg')
image16 = Image.create(image_url: 'https://cdn.images.express.co.uk/img/dynamic/11/590x/Blind-805338.jpg')
image17 = Image.create(image_url: 'http://www.collegebound.net/blog/wp-content/uploads/2013/01/shutterstock_62907706.jpg')
image18 = Image.create(image_url: 'https://static.scientificamerican.com/sciam/cache/file/2311FFA8-8F13-4DFE-A5E9B1C353CE2D78_source.jpg?w=590&h=800&D76BAC58-27F1-4C23-A10FD7F8E312E822')
image19 = Image.create(image_url: 'https://cdn.motherandbaby.co.uk/web/1/root/how-to-make-baby-laugh_w555_h555.jpg')
image20 = Image.create(image_url: 'https://lifehacks.io/wp-content/uploads/when-people-ignore-you.jpg')
image21 = Image.create(image_url: 'https://timedotcom.files.wordpress.com/2017/08/gettyimages-493656728.jpg')
image22 = Image.create(image_url: 'https://i.imgflip.com/25lg9m.jpg')