# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

quote1 = Quote.create(text: "If I had one hour left to live, I would spend it in math class because that never ends")
quote2 = Quote.create(text: "I used to think I was indecisive, but now I'm not sure")
quote3 = Quote.create(text: "Last night my internet went out, so I talked to my family. They seemed like cool people.")
quote4 = Quote.create(text: "The more you weigh, the harder you are to kidnap. Stay safe, eat cake.")
quote5 = Quote.create(text: "Before you judge a man, walk a mile in his shoes. After that who cares?... He’s a mile away and you’ve got his shoes!")
quote6 = Quote.create(text: "Better to remain silent and be thought a fool than to speak out and remove all doubt.")
quote7 = Quote.create(text: "Light travels faster than sound. This is why some people appear bright until you hear them speak.")
quote8 = Quote.create(text: "I don’t believe in astrology; I’m a Sagittarius and we’re skeptical.")
quote9 = Quote.create(text: "My opinions may have changed, but not the fact that I’m right.")
quote10 = Quote.create(text: "To be sure of hitting the target, shoot first, and call whatever you hit the target.")
quote11 = Quote.create(text: "Be who you are and say what you feel, because those who mind don’t matter and those who matter don’t mind.")
quote12 = Quote.create(text: "Money won’t buy happiness, but it will pay the salaries of a large research staff to study the problem.")
quote13 = Quote.create(text: "We never really grow up, we only learn how to act in public.")
quote14 = Quote.create(text: "I always arrive late at the office, but I make up for it by leaving early.")
quote15 = Quote.create(text: "A stockbroker urged me to buy a stock that would triple its value every year. I told him, ‘At my age, I don’t even buy green bananas.'")
quote16 = Quote.create(text: "Never under any circumstances take a sleeping pill and a laxative on the same night.")
quote17 = Quote.create(text: "Always remember that you are absolutely unique. Just like everyone else.")
quote18 = Quote.create(text: "As you get older three things happen. The first is your memory goes, and I can’t remember the other two.")
quote19 = Quote.create(text: "Always borrow money from a pessimist. He won’t expect it back.")
quote20 = Quote.create(text: "I can resist everything except temptation.")
quote21 = Quote.create(text: "Women are meant to be loved, not to be understood.")
quote22 = Quote.create(text: "I'm trying my best to see things from you're point of view, I just cant get my head that far up my ass.")
quote23 = Quote.create(text: "My mom asked me what am I going to do with my life... I don't even know what I'm going to have for lunch.")

image1 = Image.create(image_url: 'timage1.jpg')
image2 = Image.create(image_url: 'trex/app/images/timage2.jpg')
image3 = Image.create(image_url: './timage3.jpeg')
image4 = Image.create(image_url: '../images/timage4.gif')
image5 = Image.create(image_url: './images/timage5.jpg')
image6 = Image.create(image_url: './app/images/timage6.jpg')
image7 = Image.create(image_url: '../app/images/timage7.jpg')
image8 = Image.create(image_url: './images/timage8.jpg')
image9 = Image.create(image_url: './images/timage9.jpg')
image10 = Image.create(image_url: './images/timage10.jpg')
image11 = Image.create(image_url: './images/timage11.jpg')
image12 = Image.create(image_url: './images/timage12.jpg')
image13 = Image.create(image_url: './images/timage13.jpg')
image14 = Image.create(image_url: './images/timage14.jpg')
image15 = Image.create(image_url: './images/timage15.jpg')
image16 = Image.create(image_url: './images/timage16.jpg')
image17 = Image.create(image_url: './images/timage17.jpg')
image18 = Image.create(image_url: './images/timage18.jpg')
image19 = Image.create(image_url: './images/timage19.jpg')
image20 = Image.create(image_url: './images/timage20.jpg')